#
# Jobs to update packages on given Salt master environment
#
parameters:
  _param:
    jenkins_salt_api_url: "http://${_param:salt_master_host}:6969"
  jenkins:
    client:
      job:
        deploy-update-package:
          type: workflow-scm
          concurrent: true
          discard:
            build:
              keep_num: 10
            artifact:
              keep_num: 10
          display_name: "Deploy - update system package(s)"
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "gerrit"
            script: update-package.groovy
          param:
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            TARGET_SERVERS:
              type: string
              default: "*"
              description: Salt compound target to match nodes to be updated [*, G@osfamily:debian].
            TARGET_PACKAGES:
              type: string
              description: Space delimited list of packages to be updated, empty string means updating all packages to the latest version e.g. [package1=version package2=version] or [package1 package2].
