
parameters:
  jenkins:
    client:
      job:
        backupninja_restore:
          type: workflow-scm
          name: backupninja-restore
          display_name: "Backupninja restore salt-master/MaaS backup"
          discard:
            build:
              keep_num: 50
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "gerrit"
            script: backupninja-restore-pipeline.groovy
          param:
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
