parameters:
  jenkins:
    client:
      job:
        galera_backup_database:
          type: workflow-scm
          name: galera-database-backup
          display_name: "Galera database backup"
          discard:
            build:
              keep_num: 50
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "gerrit"
            script: galera-database-backup-pipeline.groovy
          param:
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            OVERRIDE_BACKUP_NODE:
              type: string
              default: "none"
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
          triggers:
            - timed: "${_param:backup_min} ${_param:backup_hour} ${_param:backup_day_of_month} ${_param:backup_month} ${_param:backup_day_of_week}"
