parameters:
  jenkins:
    client:
      job:
        deploy_trymcp:
          type: workflow-scm
          name: deploy-try-mcp
          display_name: "Deploy - TryMCP"
          discard:
            build:
              keep_num: 50
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: "gerrit"
            script: deploy-try-mcp.groovy
          param:
            COOKIECUTTER_TEMPLATE_CONTEXT:
              type: text
              default: ""
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
