parameters:
  _param:
    jenkins_master_host: ${_param:control_vip_address}
    jenkins_master_port: 8081
    jenkins_secret: "7c40abc1a7df2d26dd6b2e4421af17218df75a16fcbd5e3aa6017d9f47eaeabe"
    jenkins_master_url: http://${_param:jenkins_master_host}:${_param:jenkins_master_port}
    jenkins_slave_user: ${_param:jenkins_client_user}
    jenkins_slave_password: ${_param:jenkins_client_password}
    jenkins_slave_extra_opts: ""
