classes:
- system.docker.swarm.stack.jenkins.ssh_slave_single
parameters:
  _param:
    jenkins_slave02_node_name: ${_param:cluster_node02_name}
    jenkins_slave03_node_name: ${_param:cluster_node03_name}
  docker:
    client:
      stack:
        jenkins:
          service:
            slave02:
              environment:
                JENKINS_SLAVE_SSH_PUBKEY: ${_param:jenkins_admin_public_key}
                https_proxy: ${_param:docker_https_proxy}
                http_proxy: ${_param:docker_http_proxy}
                no_proxy: "jenkins_master,${_param:docker_no_proxy}"
              deploy:
                restart_policy:
                  condition: any
                placement:
                  constraints:
                    - "node.hostname == ${_param:jenkins_slave02_node_name}"
              image: ${_param:docker_image_jenkins_ssh_slave}
              volumes:
                - /etc/ssl/certs/:/etc/ssl/certs/:ro
                - /dev/urandom:/dev/random:ro
                - /var/run/docker.sock:/var/run/docker.sock
                - /usr/bin/docker:/usr/bin/docker:ro
                - /var/lib/jenkins:/var/lib/jenkins
            slave03:
              environment:
                JENKINS_SLAVE_SSH_PUBKEY: ${_param:jenkins_admin_public_key}
                https_proxy: ${_param:docker_https_proxy}
                http_proxy: ${_param:docker_http_proxy}
                no_proxy: "jenkins_master,${_param:docker_no_proxy}"
              deploy:
                restart_policy:
                  condition: any
                placement:
                  constraints:
                  - "node.hostname == ${_param:jenkins_slave03_node_name}"
              image: ${_param:docker_image_jenkins_ssh_slave}
              volumes:
              - /etc/ssl/certs/:/etc/ssl/certs/:ro
              - /dev/urandom:/dev/random:ro
              - /var/run/docker.sock:/var/run/docker.sock
              - /usr/bin/docker:/usr/bin/docker:ro
              - /var/lib/jenkins:/var/lib/jenkins
  jenkins:
    client:
      node:
        slave02:
          launcher:
            type: ssh
            host: jenkins_slave02
            port: 22
            username: jenkins
            credentials: ssh_slave
        slave03:
          launcher:
            type: ssh
            host: jenkins_slave03
            port: 22
            username: jenkins
            credentials: ssh_slave
